### ISSUE TITLE
I sent (first time) Ton coins to my wallet adress without comment

### ISSUE THREAD

**Issue by Kocka84** [toncenter/ton-wallet#124]
I sent 93 Ton coins to my wallet adress without comment, and they disapeared.
Can you help me to get it back?

**Comment by Kocka84** [comment]
![IMG_20220402_232504](https://user-images.githubusercontent.com/102880464/161401796-58e56cf8-6dd4-489a-8079-03f90195202e.jpg)

Sending adress:
EQBN5uMyngPBKG2mwXmfqj3rZWP2tLMaY9NsmUOiJUZ3r9_f

**Comment by Kocka84** [comment]
![IMG_20220402_233349](https://user-images.githubusercontent.com/102880464/161401955-86e4a61e-4b3f-414a-8a90-280dc7caf91c.jpg)

**Comment by Kocka84** [comment]
![Uploading IMG_20220402_234020.jpg…]()

**Comment by Kocka84** [comment]
https://explorer.toncoin.org/transaction?account=EQDanyxDbKap1YfeW2wn9wHqq48vZFIoc1rfv7TmzTFdXU-j&lt=26776656000001&hash=c0841f390f97949cd0df6bc80d5ee50a7c8fe90b5b63bbba25dbf2967cd40ae2

**Comment by DamianLedesma** [comment]
Have the same issue here, didn’t even know adding comments was necessary to do transfers. Why isn’t the solution to this issue posted in this closed ticket?
