### ISSUE TITLE
wallet.ton.org - Invoice url is being created with 1000000000X multiplied amount

### ISSUE THREAD

**Issue by artitanov** [toncenter/ton-wallet#163]
### Bug Type

Functional

### Reproduction steps

1. Navigate to https://github.com/toncenter/ton-wallet
2. Create new wallet OR use existing
3. Click in [Receive] button
4. Click on [Create Invoice] link
5. Insert any amount on Amount field (including negative amount)

### Actual result

Invoice link has combiation of wallet address and correct amount as parameter(Provided in Amount field)

### Expected result

Invoice url is being created with 1000000000X multiplied amount
<img width="276" alt="image" src="https://user-images.githubusercontent.com/45713886/190678105-bcfaa7d4-b704-4290-a094-af0fe190cf8d.png">

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: win10
- Browser Chrome
- Version 104.0.5112.102

**Comment by ProgramCrafter** [comment]
> Invoice URL is being created with 1000000000X multiplied amount

Doesn't it present amount in nanoTONs?

**Comment by EmelyanenkoK** [comment]
It is expected behavior (invoice specify amount in nanotons)
