### ISSUE TITLE
Error occured while entering wallet address

### ISSUE THREAD

**Issue by SDR4991** [toncenter/ton-wallet#179]
### Bug Type

Functional

### Reproduction steps

1. Open TON Wallet via Google Chrome Extension.
2. Click "Send"
3. Insert by Ctrl+V address of TON Wallet, where to send TONs.

### Actual result

Error appears - "Parse Transfer URL Error"

### Expected result

No Error appears

### Suggested Severity

Low

### Device

Desktop (please complete the following information):
- OS: - Windows 10
- Browser  - Chrome
- Version  - 105.0.5195.127 64 bit

### Additional Context
![TON wallet ERROR](https://user-images.githubusercontent.com/111463722/192040296-dd37ffa9-1ccb-4a5d-8928-bc74424552a9.png)

_No response_

**Comment by EmelyanenkoK** [comment]
Duplicates https://github.com/toncenter/ton-wallet/issues/164
