### ISSUE TITLE
Wallet stuck on "updating"

### ISSUE THREAD

**Issue by Zefyros94** [toncenter/ton-wallet#199]
### Bug Type

Functional

### Reproduction steps

When opening the wallet it doesn't show the balance or the send button. 

### Actual result

Pressing the update button will bring the text "updating.." visible, but it's just stuck there on the screen. 

### Expected result

Even waiting a long time, using a different browser or logging out and back in to the wallet doesn't change the result.

### Suggested Severity

Critical

### Device

Desktop (please complete the following information):
- OS: [e.g. iOS] Windows
- Browser [e.g. chrome, safari]  Chrome, Edge, Firefox doesn't make a difference.
- Version [e.g. 22] Latest?

Smartphone (please complete the following information):

**Comment by Wolfsaf** [comment]
Same problem.
![Ton wallet error](https://github.com/toncenter/ton-wallet/assets/115076083/228015ec-8869-4cec-a0b4-49d8329acaea)

**Comment by Wolfsaf** [comment]
To summarize - install a normal Ton wallet from the official website under Windows and you will be happy! Just recover the wallet with 24 words and the same password as in the Chrome extension. And forget the Web wallet like a bad dream!

**Comment by Zefyros94** [comment]
> To summarize - install a normal Ton wallet from the official website under Windows and you will be happy! Just recover the wallet with 24 words and the same password as in the Chrome extension ,after which you will immediately see your coins Ton. And forget the Web wallet like a bad dream!

Thanks for this one! Got access to my tokens now.
