### ISSUE TITLE
Uninit address in ton wallet

### ISSUE THREAD

**Issue by Romer-X** [toncenter/ton-wallet#201]
### Bug Type

Functional

### Reproduction steps

Created a new address (EQBBEQEs7u6xO670p-vgwcqnKXV1OLtFhLalsrWW4zw6cACy) in Ton Wallet (web version), deposit Ton coins 

### Actual result

Can not withdraw coins (**uninit** status of address EQBBEQEs7u6xO670p-vgwcqnKXV1OLtFhLalsrWW4zw6cACy)

### Expected result

How I can activate this address to use my deposited ton coins?

### Suggested Severity

Vulnerability

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):
- OS: [e.gg. iOS8.1]
PC, google chrome browser

**Comment by Romer-X** [comment]
issue solved

**Comment by GDsLD** [comment]
Подскажите как решили проблему?

**Comment by GDsLD** [comment]
> проблема решена

Подскажите как решили проблему

**Comment by Djarf55** [comment]
> > проблема решена
> 
> Подскажите как решили проблему

официальный ответ, надо получить и отправить ТОН , тогда контракт кошелька активируется. Вот пытаюсь
