### ISSUE TITLE
проблемы со входом

### ISSUE THREAD

**Issue by Grigjrich** [toncenter/ton-wallet#35]
не могу войти в свой кошелёк, не принимает 24 слова

**Comment by ucnobi525** [comment]
I do not remember the password

**Comment by designervoid** [comment]
@Grigjrich на латинице пытаешься войти?

**Comment by Grigjrich** [comment]
уже н пытаюсь, забил я на этот кошель, да и на тон забил, не стоит он внимания с таким отношением

**Comment by Bers2k** [comment]
столкнулся с проблемой. слетел кошелек. и не принимает 24 слова....
