### ISSUE TITLE
Не отправляются монеты

### ISSUE THREAD

**Issue by Pyrevkirill** [toncenter/ton-wallet#48]
Добрый день. Не отправляются монеты при попытке отправить на кошелек биржи. Все поля заполняю. Просто повисает на окне sending TON... Висит бесконечно. Пробовал три раза - из вэб кошелька и из расширения. Каждый раз отнимается комиссия.

В чем дело? 

![2021-12-27_18-06-14](https://user-images.githubusercontent.com/95380907/147483981-0528eb33-a7e2-4437-bcd3-dce92758a528.png)

**Comment by designervoid** [comment]
@Pyrevkirill похоже, что `баланс + комиссия за транзакцию > баланс`, но при этом блокчейн как бы совершает "работу" (пытается выполнить транзакцию), поэтому комиссия списывается.

**Comment by designervoid** [comment]
@Pyrevkirill более точно описано что происходит в этом issue:
https://github.com/toncenter/ton-wallet/issues/9#issue-627751702

**Comment by Pyrevkirill** [comment]
Ok. Спасибо

**Comment by progenitor1978** [comment]
> Добрый день. Не отправляются монеты при попытке отправить на кошелек биржи. Все поля заполняю. Просто повисает на окне sending TON... Висит бесконечно. Пробовал три раза - из вэб кошелька и из расширения. Каждый раз отнимается комиссия.
> 
> В чем дело?
> 
> ![2021-12-27_18-06-14](https://user-images.githubusercontent.com/95380907/147483981-0528eb33-a7e2-4437-bcd3-dce92758a528.png)

Приветствую. с кошелька тон средства не отправляются на кошелек биржи, но комиссия снимается. Висит окно Sending TON.
получилось только через мобильную версию на андроиде. Ни web версия, ни Chrome расширение не переводят
