### ISSUE TITLE
Need help missing transaction

### ISSUE THREAD

**Issue by noppagornj** [toncenter/ton-wallet#53]
I sent 3.9 TON to Okex exchange but forgot to input comment into transaction. 
Already contacted Okex support but they are requesting for "sending address and the block explorer link" for them to check , which is nowhere to be found. Could you please help me getting these info for me to receive my token ?

my Tonwallet address is EEQChV788IBbvsEcpDzioDwmwFe_R0Z_s44P_7U0CnFni_I-c

![Screen Shot 2565-01-02 at 3 17 23 AM](https://user-images.githubusercontent.com/96957052/147859395-b3b59d80-44a4-4dad-ab7e-4fadff53bc5e.png)

**Comment by designervoid** [comment]
@noppagornj if you need `txid` you can find your wallet address, then transaction on the `https://ton.cx`

**Comment by designervoid** [comment]
@noppagornj if you need `txid` you can find your wallet address, then you can find transaction on  `https://ton.cx`

**Comment by gjstyle11** [comment]
![image](https://user-images.githubusercontent.com/26494842/147869318-af4c1649-3b29-416e-80cd-6fb6b9ed1c5e.png)
@designervoid Привет! а что из этого txid?

**Comment by designervoid** [comment]
@gjstyle11✌️
https://github.com/toncenter/ton-wallet/issues/52#issuecomment-1003616380

**Comment by noppagornj** [comment]
Thanks for your help, the issue has been resolved.

**Comment by Sfd077** [comment]
> Спасибо за помощь, проблема решена.

А как решил проблему ?
