### ISSUE TITLE
my deposit did not go to the okex exchange and how to find transaction id?

### ISSUE THREAD

**Issue by jason0100** [toncenter/ton-wallet#57]
[https://imgur.com/a/1yKq2wj](url)

**Comment by designervoid** [comment]
@jason0100 how to find txid:
https://github.com/toncenter/ton-wallet/issues/53#issuecomment-1003619819

**Comment by designervoid** [comment]
@fpavlic https://github.com/toncenter/ton-wallet/issues/54#issuecomment-1005903163

**Comment by fpavlic** [comment]
> @fpavlic [#54 (comment)](https://github.com/toncenter/ton-wallet/issues/54#issuecomment-1005903163)

I tried sending 3.1 TON ... is that to low for sending ?

**Comment by designervoid** [comment]
@fpavlic 
![image](https://user-images.githubusercontent.com/43455658/148274854-778c212b-ece8-43f5-8333-3d904bbe5241.png)
