### ISSUE TITLE
верстка: адрес кошелька выходид за границы окна

### ISSUE THREAD

**Issue by bicedonetsk** [toncenter/ton-wallet#7]
В веб-версии кошелька (Win10, FF76.0.1), адрес выходит за границы папап-окна.
При работе с мобильного браузера, адрес кошелька при этом выходит за границы экрана

![2020-05-30_155431](https://user-images.githubusercontent.com/66169188/83328910-2bf94180-a28f-11ea-8074-18421351bdfb.png)
![2020-05-30_155958](https://user-images.githubusercontent.com/66169188/83328911-2e5b9b80-a28f-11ea-8a8e-fefceb0d092b.png)

**Comment by tolya-yanot** [comment]
fixed
