### ISSUE TITLE
Withdrawal via Bridge did not go thru

### ISSUE THREAD

**Issue by arthannemtv** [toncenter/ton-wallet#94]
Hello, I have made a withdrawal via toncoin bridge - Binance Smart Chain BEP20 - the funds left my wallet, the bridge says its okey, but the bscScan doesnt show any type of transaction from that account. Where did the TONCOINs go?

This is the contract: 
ton://transfer/Ef9NXAIQs12t2qIZ-sRZ26D977H65Ol6DQeXc5_gUNaUys5r?amount=118950000000&text=swapTo%230xFf4A615F92f3a421D753a10fF920C5dC0b368A68

This is the ton coin wallet: https://tonscan.org/address/EQDtQoPXKpi1L1qW0sKvUJXJ0hrAt7DclxCafSgLHZwCfQZ8
This is the BscScan url: https://bscscan.com/address/0xff4a615f92f3a421d753a10ff920c5dc0b368a68
If you have any type of idea... please help. 

![274324309_10159958494791108_4569880243501440995_n](https://user-images.githubusercontent.com/10519528/154871154-c11a67a7-ee75-4f3c-b5bc-20236dd2affe.jpg)

![274275852_10159958494261108_4876319907834819034_n](https://user-images.githubusercontent.com/10519528/154871155-eed4be56-bad8-4f3f-98d2-e9b0467b7aaa.jpg)

![274348522_10159958493541108_1730064696248331773_n](https://user-images.githubusercontent.com/10519528/154871158-3f01674c-fadf-4853-aa76-6f713598c04d.jpg)

**Comment by husoyo** [comment]
Same here! I lost 225 ton just like that. Please help!
